/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => QJSON
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");

// src/functions.ts
function splitByTopLevelDot(query) {
  const parts = [];
  let current = "";
  let bracketDepth = 0;
  let braceDepth = 0;
  let quote = null;
  for (const ch of query) {
    if (quote) {
      current += ch;
      if (ch === quote) {
        quote = null;
      }
      continue;
    }
    if (ch === '"' || ch === "'") {
      quote = ch;
      current += ch;
      continue;
    }
    if (ch === "[") bracketDepth++;
    if (ch === "]") bracketDepth = Math.max(0, bracketDepth - 1);
    if (ch === "{") braceDepth++;
    if (ch === "}") braceDepth = Math.max(0, braceDepth - 1);
    if (ch === "." && bracketDepth === 0 && braceDepth === 0) {
      parts.push(current);
      current = "";
    } else {
      current += ch;
    }
  }
  parts.push(current);
  return parts.filter((part) => part.length > 0);
}
function parseQuery(query) {
  const parts = splitByTopLevelDot(query.trim());
  const parsed = parts.map((part) => {
    const multiFieldMatch = part.match(/^\{([^}]+)\}$/);
    if (multiFieldMatch) {
      const fields = multiFieldMatch[1].split(",").map((f) => f.trim()).filter((f) => f.length > 0);
      if (fields.length === 0) {
        throw new Error(`Invalid multi-field selector: ${part}`);
      }
      return { type: "multiField", fields };
    }
    const filterMatch = part.match(/^(\w*)\[(.*)\]$/);
    if (filterMatch) {
      return {
        type: "filter",
        field: filterMatch[1] || null,
        condition: filterMatch[2].trim()
      };
    }
    if (/^\d+$/.test(part)) {
      return {
        type: "index",
        index: Number.parseInt(part, 10)
      };
    }
    return {
      type: "field",
      name: part
    };
  });
  let isFirst = true;
  for (const q of parsed) {
    if (isFirst) {
      isFirst = false;
      continue;
    }
    if (q.type === "filter" && !q.field) {
      throw new Error(`Filter without field: ${query}`);
    }
  }
  return parsed;
}
function splitLogicalExpression(condition) {
  const conditions = [];
  const operators = [];
  let current = "";
  let quote = null;
  for (let i = 0; i < condition.length; i++) {
    const ch = condition[i];
    const next = condition[i + 1];
    if (quote) {
      current += ch;
      if (ch === quote) {
        quote = null;
      }
      continue;
    }
    if (ch === '"' || ch === "'") {
      quote = ch;
      current += ch;
      continue;
    }
    if (ch === "&" && next === "&") {
      conditions.push(current.trim());
      operators.push("&&");
      current = "";
      i++;
      continue;
    }
    if (ch === "|" && next === "|") {
      conditions.push(current.trim());
      operators.push("||");
      current = "";
      i++;
      continue;
    }
    current += ch;
  }
  conditions.push(current.trim());
  return { conditions, operators };
}
function parseCondition(condition) {
  const split = splitLogicalExpression(condition);
  return {
    conditions: split.conditions.map((c) => parseSingleCondition(c)),
    operators: split.operators
  };
}
function parseSingleCondition(condition) {
  const trimmed = condition.trim();
  if (trimmed === "*") {
    return { key: "", operator: "*", value: "" };
  }
  const comparisonOperators = [">=", "<=", "==", "!=", ">", "<"];
  for (const operator of comparisonOperators) {
    const idx = trimmed.indexOf(operator);
    if (idx > -1) {
      const key = trimmed.slice(0, idx).trim();
      const value = trimmed.slice(idx + operator.length).trim();
      if (!key || !value) {
        throw new Error(`Invalid condition: ${condition}`);
      }
      return { key, operator, value };
    }
  }
  throw new Error(`Invalid condition: ${condition}`);
}
function parseLiteral(value) {
  const trimmed = value.trim();
  if (trimmed.startsWith('"') && trimmed.endsWith('"') || trimmed.startsWith("'") && trimmed.endsWith("'")) {
    return trimmed.slice(1, -1);
  }
  if (trimmed === "true") return true;
  if (trimmed === "false") return false;
  if (trimmed === "null") return null;
  if (trimmed !== "" && !Number.isNaN(Number(trimmed))) return Number(trimmed);
  return trimmed;
}
function executeQuery(json, parsedQuery) {
  let result = json;
  for (const part of parsedQuery) {
    if (result === void 0) {
      return void 0;
    }
    if (part.type === "field") {
      if (Array.isArray(result)) {
        result = result.map((item) => item && typeof item === "object" ? item[part.name] : void 0).filter((item) => item !== void 0);
      } else if (result && typeof result === "object") {
        result = result[part.name];
      } else {
        return void 0;
      }
      continue;
    }
    if (part.type === "index") {
      if (!Array.isArray(result)) {
        return void 0;
      }
      result = result[part.index];
      continue;
    }
    if (part.type === "multiField") {
      if (Array.isArray(result)) {
        result = result.map((item) => {
          if (!item || typeof item !== "object" || Array.isArray(item)) {
            return {};
          }
          const source = item;
          const extracted = {};
          for (const field of part.fields) {
            if (Object.prototype.hasOwnProperty.call(source, field)) {
              extracted[field] = source[field];
            }
          }
          return extracted;
        });
      } else if (result && typeof result === "object" && !Array.isArray(result)) {
        const source = result;
        const extracted = {};
        for (const field of part.fields) {
          if (Object.prototype.hasOwnProperty.call(source, field)) {
            extracted[field] = source[field];
          }
        }
        result = extracted;
      }
      continue;
    }
    if (part.type === "filter") {
      const { conditions, operators } = parseCondition(part.condition);
      let arrayToFilter = result;
      if (part.field) {
        if (!result || typeof result !== "object" || Array.isArray(result)) {
          return void 0;
        }
        arrayToFilter = result[part.field];
      }
      if (!Array.isArray(arrayToFilter)) {
        return void 0;
      }
      result = arrayToFilter.filter((item) => evaluateConditions(item, conditions, operators));
    }
  }
  return result;
}
function evaluateConditions(item, conditions, operators) {
  if (conditions.length === 0) return true;
  let result = evaluateCondition(item, conditions[0]);
  for (let i = 0; i < operators.length; i++) {
    const next = evaluateCondition(item, conditions[i + 1]);
    result = operators[i] === "&&" ? result && next : result || next;
  }
  return result;
}
function evaluateCondition(item, condition) {
  if (condition.operator === "*") {
    return true;
  }
  if (!item || typeof item !== "object" || Array.isArray(item)) {
    return false;
  }
  const obj = item;
  const itemValue = obj[condition.key];
  const queryValue = parseLiteral(condition.value);
  switch (condition.operator) {
    case "==":
      return itemValue === queryValue;
    case "!=":
      return itemValue !== queryValue;
    case ">":
    case ">=":
    case "<":
    case "<=": {
      const left = Number(itemValue);
      const right = Number(queryValue);
      if (Number.isNaN(left) || Number.isNaN(right)) {
        return false;
      }
      if (condition.operator === ">") return left > right;
      if (condition.operator === ">=") return left >= right;
      if (condition.operator === "<") return left < right;
      return left <= right;
    }
    default:
      return false;
  }
}
function formatOutput(json) {
  if (typeof json === "string") return json;
  if (json === void 0) return "undefined";
  return JSON.stringify(json, null, 2);
}
function getJSONPath(json, path) {
  if (path === "") return json;
  return path.split(".").reduce((acc, key) => {
    if (acc === null || acc === void 0) {
      return void 0;
    }
    if (typeof acc !== "object") {
      return void 0;
    }
    return acc[key];
  }, json);
}
function formatString(template, obj) {
  return template.replace(/{([^}]+)}/g, (_, name) => formatOutput(obj[name]));
}

// src/main.ts
var QJSON = class extends import_obsidian.Plugin {
  constructor() {
    super(...arguments);
    this.countTimeout = null;
    this.lastDuplicateIds = "";
  }
  async onload() {
    this.statusBarItemEl = this.addStatusBarItem();
    this.statusBarItemEl.setText("");
    this.registerEvent(this.app.workspace.on("file-open", async (file) => {
      if (file) {
        await this.countQjsonBlocks();
      } else {
        this.statusBarItemEl.setText("");
      }
    }));
    this.registerEvent(this.app.workspace.on("active-leaf-change", async () => {
      const activeFile = this.app.workspace.getActiveFile();
      if (activeFile) {
        await this.countQjsonBlocks();
      } else {
        this.statusBarItemEl.setText("");
      }
    }));
    this.registerEvent(this.app.workspace.on("editor-change", async (editor) => {
      if (this.countTimeout) {
        clearTimeout(this.countTimeout);
      }
      this.countTimeout = setTimeout(async () => {
        await this.countQjsonBlocks();
      }, 1e3);
    }));
    this.registerMarkdownCodeBlockProcessor("qjson", async (source, el) => {
      var _a, _b, _c, _d;
      if (!source.includes("#qj-id:")) {
        new import_obsidian.Notice("No ID found");
        el.createEl("pre", { text: "No ID found" });
        return;
      }
      const idMatch = source.match(/^#qj-id: (\d+)$/m);
      const id = (_a = idMatch == null ? void 0 : idMatch[1]) != null ? _a : null;
      if (!id || Number.isNaN(Number.parseInt(id, 10))) {
        new import_obsidian.Notice("ID must be a number");
        el.createEl("pre", { text: "ID must be a number" });
        return;
      }
      let query = null;
      if (source.includes("#qj-query:")) {
        const queryMatch = source.match(/^#qj-query: ([^\n\r]+)$/m);
        let queryText = (_b = queryMatch == null ? void 0 : queryMatch[1]) != null ? _b : null;
        if (!queryText) {
          new import_obsidian.Notice("No query found");
          el.createEl("pre", { text: "No query found" });
          return;
        }
        const activeFile = this.app.workspace.getActiveFile();
        const properties = activeFile ? this.app.metadataCache.getFileCache(activeFile) : null;
        if (properties && properties.frontmatter) {
          for (const key in properties.frontmatter) {
            const replacement = String(properties.frontmatter[key]);
            queryText = queryText.replace(new RegExp(`{this.${key}}`, "g"), replacement);
          }
        }
        try {
          query = parseQuery(queryText);
        } catch (error) {
          new import_obsidian.Notice(`Invalid query: ${error instanceof Error ? error.message : "unknown error"}`);
          el.createEl("pre", { text: "Invalid query" });
          return;
        }
      }
      let format = null;
      let selectedFields = null;
      if (source.includes("#qj-format:")) {
        const formatMatch = source.match(/^#qj-format: ([^\[\n\r ]+)[\t\f ]*(?:\[((?:[^\]\n\r=:,\"]*:(?:[^\]\n\r=:,\"]+|"[^\"]+")(?::[^\]\n\r=,]+)?(?:=[^\]\n\r,]+)?(?:,[^\n\r\w]*)?)+)\])?$/m);
        if (formatMatch) {
          if (formatMatch[2]) {
            const formats = formatMatch[2].split(/(?<=[^\]\n\r=:,\"]*:(?:[^\]\n\r=:,\"]+|"[^\"]+")(?::[^\]\n\r=,]+)?(?:=[^\]\n\r,]+)?)[\t\f ]*,/);
            const mappedFormats = formats.map((f) => {
              const fParts = f.match(/^([^\]\n\r=:,\"]*):(?:([^\]\n\r=:,\"]+)|"([^\"]+)")(?::([^\]\n\r=,]+))?(?:=([^\]\n\r,]+))?$/);
              if (!fParts) {
                return null;
              }
              const flags = fParts[1];
              const name = fParts[5] || null;
              const field = fParts[2] || null;
              const template = fParts[3] || null;
              const field2 = fParts[4] || null;
              return {
                header: flags.includes("h"),
                bold: flags.includes("b"),
                comma: flags.includes("c"),
                br: flags.includes("n"),
                link: flags.includes("l"),
                name,
                field,
                template,
                field2
              };
            });
            if (mappedFormats.some((f) => f === null)) {
              new import_obsidian.Notice("No format found");
              el.createEl("pre", { text: "No format found" });
              return;
            }
            selectedFields = mappedFormats;
            let first = true;
            for (const sf of selectedFields) {
              if (first) {
                first = false;
              } else {
                if (sf.header) {
                  new import_obsidian.Notice('Field format "header" is not in first position');
                  el.createEl("pre", { text: 'Field format "header" is not in first position' });
                  return;
                }
              }
              if (!sf.field && !sf.template) {
                new import_obsidian.Notice("Field format is missing field name");
                el.createEl("pre", { text: "Field format is missing field name" });
                return;
              }
              if (sf.link && !sf.field2) {
                new import_obsidian.Notice("Field format link is missing second field name");
                el.createEl("pre", { text: "Field format link is missing second field name" });
                return;
              }
              if (sf.template && !sf.name) {
                new import_obsidian.Notice("Field format with template must provide name");
                el.createEl("pre", { text: "Field format with template must provide name" });
                return;
              }
            }
          }
          format = formatMatch[1];
        } else {
          new import_obsidian.Notice("No format found");
          el.createEl("pre", { text: "No format found" });
          return;
        }
      }
      let desc = null;
      if (!source.includes("#qj-hide-id")) {
        const descMatch = source.match(/^#qj-desc: ([^\n\r]+)$/m);
        desc = (_c = descMatch == null ? void 0 : descMatch[1]) != null ? _c : "\xBB\xBB\xBB QJSON \xAB\xAB\xAB";
        el.createEl("h3", { text: desc, cls: "centerQJtext" });
        el.createEl("h4", { text: "ID: " + id, cls: "centerQJtext" });
      }
      let showJson = "notHere";
      if (source.includes("#qj-show-json")) {
        showJson = "";
      }
      if (source.includes("#qj-file:")) {
        const file = source.match(/^#qj-file: ([^\n\r]+)$/m);
        if (file) {
          try {
            source = await this.app.vault.adapter.read(file[1]);
          } catch (e) {
            const activeFile = this.app.workspace.getActiveFile();
            if (!activeFile || !activeFile.parent) {
              new import_obsidian.Notice("No file open to resolve relative JSON path");
              el.createEl("pre", { text: "No file open to resolve relative JSON path" });
              return;
            }
            const filePath = activeFile.parent.path + "/";
            try {
              source = await this.app.vault.adapter.read(filePath + file[1]);
            } catch (e2) {
              new import_obsidian.Notice("No file given");
              el.createEl("pre", { text: "No file given" });
              return;
            }
          }
        } else {
          new import_obsidian.Notice("No file given");
          el.createEl("pre", { text: "No file given" });
          return;
        }
      } else {
        source = source.replace(/^#qj-[a-z]+(: )?.*$/gm, "");
      }
      let json;
      try {
        json = JSON.parse(source);
      } catch (e) {
        new import_obsidian.Notice("Invalid JSON");
        el.createEl("pre", { text: "Invalid JSON" });
        return;
      }
      let result = json;
      let fieldResult = !Array.isArray(result);
      if (query) {
        result = executeQuery(json, query);
        fieldResult = ((_d = query[query.length - 1]) == null ? void 0 : _d.type) === "field";
      }
      if (!format || format === "json") {
        el.createEl("pre", { text: formatOutput(result), cls: "QJSON-" + id + " cdQjson " + showJson });
      } else {
        if (fieldResult) {
          if (selectedFields) {
            new import_obsidian.Notice("Field queries currently ignore field formats");
          }
          if (format === "list") {
            const ul = el.createEl("ul");
            if (typeof result === "string") {
              ul.createEl("li", { text: result });
            } else if (Array.isArray(result)) {
              for (let i = 0; i < result.length; i++) {
                ul.createEl("li", { text: formatOutput(result[i]) });
              }
            } else if (result && typeof result === "object") {
              for (const [key, value] of Object.entries(result)) {
                const li = ul.createEl("li");
                li.appendText(`${key}: ${formatOutput(value)}`);
              }
            } else {
              new import_obsidian.Notice("unsupported object type");
            }
          } else if (format === "table") {
            const table = el.createEl("table");
            const tbody = table.createEl("tbody");
            if (typeof result === "string") {
              const tr = tbody.createEl("tr");
              tr.createEl("td", { text: result });
            } else if (Array.isArray(result)) {
              for (let i = 0; i < result.length; i++) {
                const tr = tbody.createEl("tr");
                tr.createEl("td", { text: formatOutput(result[i]) });
              }
            } else if (result && typeof result === "object") {
              for (const [key, value] of Object.entries(result)) {
                const tr = tbody.createEl("tr");
                tr.createEl("th", { text: key });
                tr.createEl("td", { text: formatOutput(value) });
              }
            } else {
              new import_obsidian.Notice("unsupported object type");
            }
          } else if (format === "img") {
            if (typeof result === "string") {
              el.createEl("img", { attr: { src: result } });
            } else if (Array.isArray(result)) {
              let notString = false;
              for (let i = 0; i < result.length; i++) {
                if (typeof result[i] === "string") {
                  el.createEl("img", { attr: { src: result[i], width: 100, height: 100 } });
                } else {
                  notString = true;
                }
              }
              if (notString) {
                new import_obsidian.Notice("one or more entries could not be rendered");
              }
            } else {
              new import_obsidian.Notice('format "img" does not support objects');
            }
          }
        } else {
          if (!Array.isArray(result)) {
            new import_obsidian.Notice("Table & list can only be created from array");
            el.createEl("pre", { text: "Table & list can only be created from array" });
            return;
          }
          let arrayResult = result;
          if (!selectedFields && arrayResult.length > 0) {
            if (Array.isArray(arrayResult[0]) || typeof arrayResult[0] !== "object") {
              arrayResult = arrayResult.map((e) => ({ entry: e }));
              result = arrayResult;
            }
            selectedFields = Object.entries(arrayResult[0]).map(([k]) => {
              return {
                header: false,
                bold: false,
                comma: false,
                br: false,
                link: false,
                name: null,
                field: k,
                template: null,
                field2: null
              };
            });
          }
          if (!selectedFields || selectedFields.length === 0) {
            new import_obsidian.Notice("No fields found to render");
            el.createEl("pre", { text: "No fields found to render" });
            return;
          }
          let oEl;
          let titleNum = 1;
          if (format === "list") {
            if (selectedFields[0].header && selectedFields[0].name) {
              formatElement(el, selectedFields[0], {}, selectedFields[0].name);
            }
            oEl = el.createEl("ul", { attr: { style: "list-style-position: outside;" } });
          } else if (format === "table") {
            const table = el.createEl("table");
            const thead = table.createEl("thead");
            oEl = table.createEl("tbody");
            const tr = thead.createEl("tr");
            for (const select of selectedFields) {
              const name = select.name || select.field || "";
              const td = tr.createEl("td");
              td.createEl("b", { text: name });
            }
          } else {
            return;
          }
          let eEl;
          for (const entry of arrayResult) {
            if (format === "list") {
              const hEl = oEl.createEl("li");
              if (selectedFields[0].header) {
                formatElement(hEl, selectedFields[0], entry != null ? entry : {});
              } else {
                hEl.appendText("" + titleNum++);
              }
              eEl = hEl.createEl("ul", { attr: { style: "list-style-position: inside;" } });
            } else if (format === "table") {
              eEl = oEl.createEl("tr");
            } else {
              return;
            }
            for (const select of selectedFields) {
              if (format === "list") {
                if (select.header) {
                  continue;
                }
                const fEl = eEl.createEl("li");
                if (select.name) {
                  fEl.appendText(select.name);
                } else {
                  fEl.appendText(select.field || "");
                }
                fEl.appendText(": ");
                formatElement(fEl, select, entry != null ? entry : {});
              } else if (format === "table") {
                let fEl;
                if (select.header) {
                  fEl = eEl.createEl("th");
                } else {
                  fEl = eEl.createEl("td");
                }
                formatElement(fEl, select, entry != null ? entry : {});
              }
            }
          }
        }
      }
    });
    this.registerEvent(this.app.workspace.on("editor-change", async (editor) => {
      const cursor = editor.getCursor();
      const line = editor.getLine(cursor.line);
      const lastChar = line[line.length - 1];
      if (lastChar !== ";" && lastChar !== "." && lastChar !== ">" && lastChar !== "]") return;
      const atIndex = line.lastIndexOf("@");
      if (atIndex === -1) return;
      const queryPart = line.slice(atIndex);
      const match = queryPart.match(/^@([^>]+)>(.*)$/);
      if (!match) return;
      const id = match[1].trim();
      const rawPath = match[2];
      const path = rawPath.length > 0 ? rawPath.slice(0, -1).trim() : "";
      const json = await this.resolveJsonSource(id);
      if (json === void 0) return;
      let value = this.evaluateInlinePath(json, path);
      if (lastChar !== ";") {
        if (value !== void 0) {
          const notice = document.querySelector(".notice");
          if (notice) notice.remove();
          if (typeof value === "string" || typeof value === "number" || typeof value === "boolean") {
            new import_obsidian.Notice(value.toString());
          } else if (value && typeof value === "object") {
            const keys = Object.keys(value);
            const keysAreNumbers = keys.every((key) => !Number.isNaN(Number.parseInt(key, 10)));
            if (keysAreNumbers) {
              new import_obsidian.Notice("Total Keys: " + keys.length);
            } else {
              new import_obsidian.Notice("Total Keys: " + keys.length + "\n____________\n" + keys.join("\n"));
            }
          }
        }
      } else {
        const replaceEnd = { line: cursor.line, ch: line.length };
        const stringValue = typeof value === "string" ? value : formatOutput(value);
        editor.replaceRange(stringValue, { line: cursor.line, ch: atIndex }, replaceEnd);
      }
    }));
  }
  async resolveJsonSource(id) {
    if (!Number.isNaN(Number.parseInt(id, 10)) && !id.includes(".json")) {
      const jsonEl = document.querySelector(".QJSON-" + id);
      if (!(jsonEl == null ? void 0 : jsonEl.textContent)) {
        return void 0;
      }
      try {
        return JSON.parse(jsonEl.textContent);
      } catch (e) {
        new import_obsidian.Notice("Invalid JSON source for ID " + id);
        return void 0;
      }
    }
    try {
      const source = await this.app.vault.adapter.read(id);
      return JSON.parse(source);
    } catch (e) {
      try {
        const activeFile = this.app.workspace.getActiveFile();
        if (!activeFile || !activeFile.parent) {
          return void 0;
        }
        const source = await this.app.vault.adapter.read(`${activeFile.parent.path}/${id}`);
        return JSON.parse(source);
      } catch (e2) {
        new import_obsidian.Notice(`Unable to load JSON file: ${id}`);
        return void 0;
      }
    }
  }
  evaluateInlinePath(json, path) {
    if (!path) {
      return json;
    }
    try {
      return executeQuery(json, parseQuery(path));
    } catch (e) {
      const cleanPath = path.replace(/\*/g, "").replace(/\[\]/g, "");
      return getJSONPath(json, cleanPath);
    }
  }
  async countQjsonBlocks() {
    const activeFile = this.app.workspace.getActiveFile();
    if (!activeFile) {
      this.statusBarItemEl.setText("");
      return;
    }
    try {
      const content = await this.app.vault.read(activeFile);
      const qjsonBlockRegex = /```qjson[\s\S]*?#qj-id:\s*(\d+)/g;
      const matches = content.matchAll(qjsonBlockRegex);
      const ids = /* @__PURE__ */ new Set();
      const duplicateIds = /* @__PURE__ */ new Set();
      for (const match of matches) {
        const id = match[1];
        if (ids.has(id)) {
          duplicateIds.add(id);
        } else {
          ids.add(id);
        }
      }
      if (duplicateIds.size > 0) {
        const duplicateKey = Array.from(duplicateIds).sort().join(",");
        if (duplicateKey !== this.lastDuplicateIds) {
          new import_obsidian.Notice(`Duplicate QJSON IDs found: ${Array.from(duplicateIds).join(", ")}`);
          this.lastDuplicateIds = duplicateKey;
        }
      } else {
        this.lastDuplicateIds = "";
      }
      const uniqueCount = ids.size;
      if (uniqueCount > 0) {
        this.statusBarItemEl.setText(`${uniqueCount} qjson`);
      } else {
        this.statusBarItemEl.setText("");
      }
    } catch (error) {
      console.error("Error counting QJSON blocks:", error);
      this.statusBarItemEl.setText("");
    }
  }
  onunload() {
    this.statusBarItemEl.setText("");
  }
};
function formatElement(parent, format, json, text) {
  var _a, _b;
  if (!text) {
    if (format.field) {
      const textJson = json[format.field];
      if (Array.isArray(textJson)) {
        text = textJson.map((j) => formatOutput(j));
      } else {
        text = formatOutput(textJson);
      }
    } else if (format.template) {
      text = formatString(format.template, json);
    } else {
      text = "";
    }
  }
  const el = format.bold ? parent.createEl("b") : parent;
  if (Array.isArray(text)) {
    let idx = 0;
    for (const t of text) {
      if (format.link) {
        const links = format.field2 ? json[format.field2] : void 0;
        const href = Array.isArray(links) ? String((_a = links[idx]) != null ? _a : "") : "";
        el.createEl("a", { text: t, href });
      } else {
        el.appendText(t);
      }
      if (idx < text.length - 1) {
        if (format.comma) {
          el.appendText(", ");
        } else if (format.br) {
          el.createEl("br");
        } else {
          el.appendText(" ");
        }
      }
      idx++;
    }
  } else {
    if (format.link) {
      const href = format.field2 ? String((_b = json[format.field2]) != null ? _b : "") : "";
      el.createEl("a", { text, href });
    } else {
      el.appendText(text);
    }
  }
}

/* nosourcemap */